### ISSUE TITLE
Missing decimal readings

### ISSUE THREAD

**Issue by rorso** [j0ta29/esphome#10]
I finally got a version running with my Vitocal 333 :-D

However, I seem to miss the decimal readings of temperatures, although they show up in the log.

```
[00:22:21][D][OptolinkSensorBase:105]: Datapoint optolink - Boiler Temperatur oben: 48.500000
[00:22:22][D][sensor:094]: 'Boiler Temperatur oben': Sending state 48.50000 °C with 0 decimals of accuracy

```
Instead I get flipping numbers between 48.0 and 49.0. It does not help, if I configure the display precision to "xx,x", as obviously the decimal is dropped deeper in the program.

The key probably is the **with 0 decimals of accuracy**, as the idea of having a divider by 10 for an integer return IS to create a decimal.

My sensor setting for this example is:

```
  - platform: optolink
    name: Boiler Temperatur oben
    address: 0x010D
    bytes: 2
    div_ratio: 10
    unit_of_measurement: °C
    device_class: temperature

```

![image](https://github.com/j0ta29/esphome/assets/4092020/f2b83e6a-d82b-4ab9-a51e-3cd8811263a1)

I confess, I occasionally do miss something obvious, but usually the problem is the reverse, i.e. to get rid of a bunch of excess decimals.
Do I have to state the data type "float" somewhere within the optolink sensor definition?

**Comment by j0ta29** [comment]
Try 
```
 accuracy_decimals: 1 
```
It's an attribute of https://esphome.io/components/sensor/

**Comment by rorso** [comment]
Thank you. I will try that later this evening.

I did override "the default" via the property setting, as the "sensor" docs state that this is only a display suggestion and does not affect the internally stored precision.

> accuracy_decimals (Optional, int): Manually set the number of decimals to use when reporting values. This does not impact the actual value reported to Home Assistant, it just sets the number of decimals to use when displaying it.

If however, the component does read this optional setting from the sensor definition to adjust the stored value - then setting it there will make a difference.

![image](https://github.com/j0ta29/esphome/assets/4092020/9800171e-6efc-42f6-972e-7d27b68bcab2)

**Comment by rorso** [comment]
Perfect!

`[22:34:47][D][sensor:094]: 'Vorlauf HK1': Sending state 29.20000 °C with 1 decimals of accuracy`
