### ISSUE TITLE
[Bug] Strange behavior when using text sensor at Friday/Saturday/Sunday

### ISSUE THREAD

**Issue by Skarabaen** [j0ta29/esphome#13]
Hello @J0ta29,
thank you for your work at optolink. It works fine, but I think I have found a bug or something else.

I`m using esphome on a nodemcu V2 with a 20CB heater unit.  

> substitutions:
>   device_name: viessmann
>   device_description: "Viessmann Optolink"
> 
> esphome:
>   name: '${device_name}'
>   friendly_name: vitoconnect
>   platform: ESP8266
>   board: nodemcuv2
> 
> external_components:
>   - source:
>       type: git
>       url: https://github.com/j0ta29/esphome
>       ref: optolink
>     components: [ optolink ]
> 
> # Enable logging
> logger:
>   hardware_uart: UART0
>   baud_rate: 0
>   level: WARN
> 
> # Enable Home Assistant API
> api:
>   encryption:
>     key: ""
> 
> ota:
>   password: ""
> 
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
>   use_address: 
> 
>   # Enable fallback hotspot (captive portal) in case wifi connection fails
>   ap:
>     ssid: "Viessmann Fallback"
>     password: ""
> 
> captive_portal:
> 
> 
> optolink:
>   protocol: P300
> 
> text:
> #############################
>   - platform: optolink
>     name: "HeizPlanMo"
>     address: 0x2000
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: MONDAY
>     icon: mdi:shower
>     update_interval: 172s
>   - platform: optolink
>     name: "HeizPlanDi"
>     address: 0x2008
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: Tuesday
>     icon: mdi:shower
>     update_interval: 175s
>   - platform: optolink
>     name: "HeizPlanMi"
>     address: 0x2010
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: Wednesday
>     icon: mdi:shower
>     update_interval: 178s
>   - platform: optolink
>     name: "HeizPlanDo"
>     address: 0x2018
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: Thursday
>     icon: mdi:shower
>     update_interval: 161s
>   - platform: optolink
>     name: "HeizPlanFr"
>     address: 0x2020
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: Friday
>     icon: mdi:shower
>     update_interval: 165s
>   - platform: optolink
>     name: "HeizPlanSa"
>     address: 0x2028
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: Saturday
>     icon: mdi:shower
>     update_interval: 170s
>   - platform: optolink
>     name: "HeizPlanSo"
>     address: 0x2030
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: Sunday
>     icon: mdi:shower
>     update_interval: 175s

I´m getting always the error code

> [W][optolink.datapoint_component:137]: 3. read request for ZirkuPlanFr rejected  due to outstanding running request - increase update_interval!

with the sensors for Friday/Saturday/Sunday and also for Warmwater time and Warmwater circulation time. Only these 3 days.

I tried a lot. I only use one friday sensor, changed the update_interval from 60s to 500s, always the same error message and the value "unknown" at home assistant. 

I can fix this issue if I set

>   - platform: optolink
>     name: "HeizPlanFr"
>     address: 0x2020
>     bytes: 56
>     type: DAY_SCHEDULE
>     day_of_week: **Monday**
>     icon: mdi:shower
>     update_interval: 165s

So set the day_of_week variable to Monday will fix this issue and I can see the right values. I don`t know which impact this has. 

If you need more information or debugging, let me know.

**Comment by j0ta29** [comment]
The address values are the same for all days of week (0x2000). The address offset for is calculated within the component.
